import { ITheme } from '../contexts/Theme'

const color = (
  index: number = 0,
  alpha: number = 1,
  red: number = 255,
  green: number = 127.5,
  blue: number = 8
) => `rgba(${index * red}, ${index * green}, ${index * blue}, ${alpha})`

export const BlueHarvester: ITheme = {
  global: {
    radius: 3,
    fonts: 15,
  },
  button: {
    label: color(0.85),
    labelHover: color(0.95),
    labelDisabled: color(0.4),
    background: color(0.55),
    backgroundMinor: color(0.45),
    backgroundDisabled: color(0.25),
    backgroundHover: color(0.6),
    shadow: `0 0 13px -3px ${color(0.15, 0.15)}`,
    border: `none`,
  },
  input: {
    label: color(0.8),
    helper: color(0.6),
    placeholder: color(0.55),
    value: color(0.75),
    valueHover: color(0.95),
    background: color(0.3),
    backgroundHover: color(0.25),
    backgroundDisabled: color(0.35),
    shadow: `0 0 13px -3px ${color(0, 0.25)}`,
    border: `none`,
    on: color(0.6),
    off: color(0.2),
  },
  gadgets: {
    title: color(0.75),
    subtitle: color(0.6),
    branding: color(0.55),
    brandingHover: color(0.35),
    header: color(0.4),
    border: `none`,
    background: color(0.35),
    scrollbar: color(0.45),
  },
  page: {
    title: color(0.8),
    subtitle: color(0.65),
    branding: color(0.55),
    brandingHover: color(0.35),
    label: color(0.65),
    labelHover: color(0.75),
    header: color(0.4),
    headerHover: color(0.45),
    border: `none`,
    background: color(0.35),
    scrollbar: color(0.45),
  },
  sideBar: {
    title: color(0.7),
    footer: color(0.55),
    options: color(0.55),
    optionsHover: color(0.75),
    optionsFocused: color(0.65),
    background: color(0.3),
    backgroundHover: color(0.35),
    border: `none`,
  },
  searchBar: {
    label: color(0.75),
    labelHover: color(0.85),
    labelDisabled: color(0.45),
    placeholder: color(0.65),
    background: color(0.45),
    backgroundHover: color(0.5),
    backgroundDisabled: color(0.3),
    border: `1px solid ${color(0.4, 0.2)}`,
  },
  iconBar: {
    icon: color(0.65),
    iconHover: color(0.85),
    iconFocused: color(0.75),
    iconBackground: color(0.25),
    iconBackgroundHover: color(0.35),
    background: color(0.25),
    border: `none`,
  },
  pointer: {
    label: color(0.9),
    helper: color(0.75),
    background: color(0.5),
    shadow: `0 0 13px -3px ${color(0.15, 0.15)}`,
    border: `none`,
  },
  menu: {
    label: color(0.9),
    helper: color(0.75),
    background: color(0.5),
    backgroundHover: color(0.6),
    border: `none`,
  },
  modal: {
    background: color(0.1),
    shadow: `0 0 13px -3px ${color(0.15, 0.15)}`,
    border: `none`,
    cover: color(0.5, 0.5),
  },
  snippet: {
    label: color(0.7),
    value: color(0.85),
    arrow: color(0.7),
    background: color(0.45),
    backgroundHover: color(0.5),
    border: `1px solid ${color(0.3, 0.4)}`,
  },
  table: {
    label: color(0.75),
    value: color(0.9),
    header: color(0.5),
    headerHover: color(0.55),
    background: color(0.535),
    backgroundHover: color(0.57),
    border: `1px solid ${color(0.465)}`,
  },
  empty: {
    label: color(0.85),
    helper: color(0.65),
    background: color(0.45),
    shadow: `0 0 13px -3px ${color(0.15, 0.15)}`,
    border: `1px solid ${color(0.25, 0.5)}`,
    cover: `linear-gradient(to top, ${color(0.4)}, ${color(
      0.4,
      0.95
    )} 65%, ${color(0.4, 0.7)})`,
  },
  toaster: {
    label: color(1),
    helper: color(0.75),
    background: color(0.45),
    backgroundHover: color(0.5),
    shadow: `0 0 13px -3px ${color(0.15, 0.15)}`,
    border: `1px solid ${color(0.3, 0.4)}`,
  },
  poster: {
    label: color(0.85),
    helper: color(0.65),
    background: color(0.45),
    border: `none`,
  },
  focus: {
    label: color(0.85),
    helper: color(0.65),
    background: color(0.45),
  },
}
